package ph.com.gs3.loyaltycustomer.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PROMO_IMAGES".
 */
public class PromoImages {

    private Long id;
    private String name;
    private String description;
    private String image_file;

    public PromoImages() {
    }

    public PromoImages(Long id) {
        this.id = id;
    }

    public PromoImages(Long id, String name, String description, String image_file) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.image_file = image_file;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImage_file() {
        return image_file;
    }

    public void setImage_file(String image_file) {
        this.image_file = image_file;
    }

}
