package ph.com.gs3.loyaltycustomer.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STORE".
 */
public class Store {

    private Long id;
    private String device_id;
    private String name;

    public Store() {
    }

    public Store(Long id) {
        this.id = id;
    }

    public Store(Long id, String device_id, String name) {
        this.id = id;
        this.device_id = device_id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDevice_id() {
        return device_id;
    }

    public void setDevice_id(String device_id) {
        this.device_id = device_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
