package ph.com.gs3.loyaltycustomer.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRANSACTION".
 */
public class Transaction {

    private Long id;
    private Integer store_id;
    private String customer_id;
    private Float amount;
    private Float total_discount;
    private java.util.Date transaction_date;

    public Transaction() {
    }

    public Transaction(Long id) {
        this.id = id;
    }

    public Transaction(Long id, Integer store_id, String customer_id, Float amount, Float total_discount, java.util.Date transaction_date) {
        this.id = id;
        this.store_id = store_id;
        this.customer_id = customer_id;
        this.amount = amount;
        this.total_discount = total_discount;
        this.transaction_date = transaction_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getStore_id() {
        return store_id;
    }

    public void setStore_id(Integer store_id) {
        this.store_id = store_id;
    }

    public String getCustomer_id() {
        return customer_id;
    }

    public void setCustomer_id(String customer_id) {
        this.customer_id = customer_id;
    }

    public Float getAmount() {
        return amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }

    public Float getTotal_discount() {
        return total_discount;
    }

    public void setTotal_discount(Float total_discount) {
        this.total_discount = total_discount;
    }

    public java.util.Date getTransaction_date() {
        return transaction_date;
    }

    public void setTransaction_date(java.util.Date transaction_date) {
        this.transaction_date = transaction_date;
    }

}
