package ph.com.gs3.loyaltycustomer.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRANSACTION_PRODUCT".
 */
public class TransactionProduct {

    private Long id;
    private Long sales_id;
    private Long product_id;
    private String product_name;
    private Float unit_cost;
    private String sku;
    private Integer quantity;
    private Float sub_total;
    private String sale_type;

    public TransactionProduct() {
    }

    public TransactionProduct(Long id) {
        this.id = id;
    }

    public TransactionProduct(Long id, Long sales_id, Long product_id, String product_name, Float unit_cost, String sku, Integer quantity, Float sub_total, String sale_type) {
        this.id = id;
        this.sales_id = sales_id;
        this.product_id = product_id;
        this.product_name = product_name;
        this.unit_cost = unit_cost;
        this.sku = sku;
        this.quantity = quantity;
        this.sub_total = sub_total;
        this.sale_type = sale_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSales_id() {
        return sales_id;
    }

    public void setSales_id(Long sales_id) {
        this.sales_id = sales_id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public String getProduct_name() {
        return product_name;
    }

    public void setProduct_name(String product_name) {
        this.product_name = product_name;
    }

    public Float getUnit_cost() {
        return unit_cost;
    }

    public void setUnit_cost(Float unit_cost) {
        this.unit_cost = unit_cost;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Float getSub_total() {
        return sub_total;
    }

    public void setSub_total(Float sub_total) {
        this.sub_total = sub_total;
    }

    public String getSale_type() {
        return sale_type;
    }

    public void setSale_type(String sale_type) {
        this.sale_type = sale_type;
    }

}
