package ph.com.gs3.loyaltycustomer.models.sqlite.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRANSACTION_PRODUCT".
*/
public class TransactionProductDao extends AbstractDao<TransactionProduct, Long> {

    public static final String TABLENAME = "TRANSACTION_PRODUCT";

    /**
     * Properties of entity TransactionProduct.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sales_id = new Property(1, Integer.class, "sales_id", false, "SALES_ID");
        public final static Property Product_id = new Property(2, Integer.class, "product_id", false, "PRODUCT_ID");
        public final static Property Product_name = new Property(3, String.class, "product_name", false, "PRODUCT_NAME");
        public final static Property Unit_cost = new Property(4, Float.class, "unit_cost", false, "UNIT_COST");
        public final static Property Sku = new Property(5, String.class, "sku", false, "SKU");
        public final static Property Quantity = new Property(6, Integer.class, "quantity", false, "QUANTITY");
        public final static Property Sub_total = new Property(7, Float.class, "sub_total", false, "SUB_TOTAL");
        public final static Property Sale_type = new Property(8, String.class, "sale_type", false, "SALE_TYPE");
    };


    public TransactionProductDao(DaoConfig config) {
        super(config);
    }
    
    public TransactionProductDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRANSACTION_PRODUCT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SALES_ID\" INTEGER," + // 1: sales_id
                "\"PRODUCT_ID\" INTEGER," + // 2: product_id
                "\"PRODUCT_NAME\" TEXT," + // 3: product_name
                "\"UNIT_COST\" REAL," + // 4: unit_cost
                "\"SKU\" TEXT," + // 5: sku
                "\"QUANTITY\" INTEGER," + // 6: quantity
                "\"SUB_TOTAL\" REAL," + // 7: sub_total
                "\"SALE_TYPE\" TEXT);"); // 8: sale_type
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANSACTION_PRODUCT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TransactionProduct entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer sales_id = entity.getSales_id();
        if (sales_id != null) {
            stmt.bindLong(2, sales_id);
        }
 
        Integer product_id = entity.getProduct_id();
        if (product_id != null) {
            stmt.bindLong(3, product_id);
        }
 
        String product_name = entity.getProduct_name();
        if (product_name != null) {
            stmt.bindString(4, product_name);
        }
 
        Float unit_cost = entity.getUnit_cost();
        if (unit_cost != null) {
            stmt.bindDouble(5, unit_cost);
        }
 
        String sku = entity.getSku();
        if (sku != null) {
            stmt.bindString(6, sku);
        }
 
        Integer quantity = entity.getQuantity();
        if (quantity != null) {
            stmt.bindLong(7, quantity);
        }
 
        Float sub_total = entity.getSub_total();
        if (sub_total != null) {
            stmt.bindDouble(8, sub_total);
        }
 
        String sale_type = entity.getSale_type();
        if (sale_type != null) {
            stmt.bindString(9, sale_type);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TransactionProduct readEntity(Cursor cursor, int offset) {
        TransactionProduct entity = new TransactionProduct( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // sales_id
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // product_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // product_name
            cursor.isNull(offset + 4) ? null : cursor.getFloat(offset + 4), // unit_cost
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // sku
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // quantity
            cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7), // sub_total
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // sale_type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TransactionProduct entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSales_id(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setProduct_id(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setProduct_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUnit_cost(cursor.isNull(offset + 4) ? null : cursor.getFloat(offset + 4));
        entity.setSku(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setQuantity(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setSub_total(cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7));
        entity.setSale_type(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TransactionProduct entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TransactionProduct entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
