package ph.com.gs3.loyaltycustomer.models.sqlite.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ph.com.gs3.loyaltycustomer.models.sqlite.dao.TransactionHasRewards;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRANSACTION_HAS_REWARDS".
*/
public class TransactionHasRewardsDao extends AbstractDao<TransactionHasRewards, Long> {

    public static final String TABLENAME = "TRANSACTION_HAS_REWARDS";

    /**
     * Properties of entity TransactionHasRewards.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Reward_id = new Property(1, Long.class, "reward_id", false, "REWARD_ID");
        public final static Property Sales_transaction_number = new Property(2, String.class, "sales_transaction_number", false, "SALES_TRANSACTION_NUMBER");
    };


    public TransactionHasRewardsDao(DaoConfig config) {
        super(config);
    }
    
    public TransactionHasRewardsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRANSACTION_HAS_REWARDS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"REWARD_ID\" INTEGER," + // 1: reward_id
                "\"SALES_TRANSACTION_NUMBER\" TEXT);"); // 2: sales_transaction_number
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANSACTION_HAS_REWARDS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TransactionHasRewards entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long reward_id = entity.getReward_id();
        if (reward_id != null) {
            stmt.bindLong(2, reward_id);
        }
 
        String sales_transaction_number = entity.getSales_transaction_number();
        if (sales_transaction_number != null) {
            stmt.bindString(3, sales_transaction_number);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TransactionHasRewards readEntity(Cursor cursor, int offset) {
        TransactionHasRewards entity = new TransactionHasRewards( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // reward_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // sales_transaction_number
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TransactionHasRewards entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setReward_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSales_transaction_number(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TransactionHasRewards entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TransactionHasRewards entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
